name: date_time_popover
description: Flutter Day and Time Picker
version: 1.2.7+4

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  after_layout: ^1.0.7+2
  bloc: ^4.0.0
  enum_to_string: 1.0.9
  equatable: ^1.1.1
  flutter_bloc: ^4.0.0
  flutter_modular: ^1.1.2
  intl: ^0.16.1
  cupertino_icons: ^0.1.3
  mode_theme:
    git:
      url: https://github.com/GitHubStuff/mode_theme.git
  tracers:
    git:
      url: https://github.com/GitHubStuff/tracers.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
