name: flutter_date_time_popover
description: Flutter Day Picker
version: 1.2.0+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_project_package:
    git:
      url: https://github.com/GitHubStuff/flutter_project_package.git
  after_layout: ^1.0.7+2
  bloc: ^4.0.0
  enum_to_string: 1.0.9
  equatable: ^1.1.1
  flutter_bloc: ^4.0.0
  flutter_modular: ^1.1.2
  intl: ^0.16.1
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
